[package]
name = "friday-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
dirs = "5.0.0"
env_logger = "0.10.0"
log = "0.4.17"
thiserror = "1.0.40"
