unstable_features=true

reorder_imports=true
imports_layout="HorizontalVertical"
imports_granularity="Crate"
group_imports="StdExternalCrate"

use_small_heuristics="max"
wrap_comments=true
blank_lines_upper_bound=1

format_code_in_doc_comments=true
format_macro_matchers=true
format_macro_bodies=true

condense_wildcard_suffixes=true
use_field_init_shorthand=true
use_try_shorthand=true