spin_manifest_version = "1"
authors = ["Tobias Brumhard <code@brumhard.com>"]
description = ""
name = "friday"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "friday"
source = "target/wasm32-wasi/release/friday_spin.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release --manifest-path=crates/friday_spin/Cargo.toml"
watch = ["crates/**/*.rs", "Cargo.toml"]
